name: Go
on: [push]
jobs:
  Darwin:
    runs-on: macos-latest
    steps:
    - name: Set up Go 
      uses: actions/setup-go@v1
      with:
        go-version: 1.19
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        ref: master

    - name: Build
      run: |
        env CGO_ENABLED=1 GOOS=darwin go build -ldflags="-s -w"  -o darwin-amd64/yairc
        env GOPATH=$PWD/gopath go get -u github.com/missdeer/cicdutil

    - name: Upload artifact yairc-darwin-amd64
      uses: actions/upload-artifact@v1.0.0
      with:
        name: yairc-darwin-amd64
        path: darwin-amd64

    - name: Remove old artifacts
      run: |
        gopath/bin/cicdutil -p github -u missdeer -t ${{ secrets.GH_TOKEN }} -r yairc -k 0 -a delete

  WindowsLinux:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 
      uses: actions/setup-go@v2
      with:
        go-version: 1.19
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        ref: master
        
    - name: Set up mingw toolchain for windows
      run: |
        sudo apt-get update -qq ;
        sudo apt-get install -qq g++-mingw-w64-i686 ;
        sudo apt-get install -qq g++-mingw-w64-x86-64 ;
        
    - name: Build
      run: |
        env CGO_ENABLED=1 GOARCH=amd64 GOOS=linux go build -ldflags="-s -w"  -o linux-amd64/yairc 
        env CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ LD=x86_64-w64-mingw32-ld GOARCH=amd64 GOOS=windows go build  -o windows-amd64/yairc.exe 
        env CGO_ENABLED=1 CC=i686-w64-mingw32-gcc CXX=i686-w64-mingw32-g++ LD=i686-w64-mingw32-ld GOARCH=386 GOOS=windows go build  -o windows-386/yairc.exe

    - name: Upload artifact yairc-linux-amd64
      uses: actions/upload-artifact@v1.0.0
      with:
        name: yairc-linux-amd64
        path: linux-amd64

    - name: Upload artifact yairc-windows-amd64
      uses: actions/upload-artifact@v1.0.0
      with:
        name: yairc-windows-amd64
        path: windows-amd64

    - name: Upload artifact yairc-windows-386
      uses: actions/upload-artifact@v1.0.0
      with:
        name: yairc-windows-386
        path: windows-386
